# Site settings
title: Terrence Wood
email: terrence.wood@terrencewood.com
description: "Mobile web maker. Design, urbanism, futurology, and the human condition."
baseurl: ""
url: "http://terrencewood.com"

exclude: ['README.md', 'package.json', 'node_modules', 'bower_components']

# Build settings
markdown: kramdown
permalink: title
relative_permalinks: false


# prose.io

prose:
  rooturl: '_posts'
  siteurl: 'http://terrencewood.com'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""