# Site settings
title: Terrence Wood
email: terrence.wood@terrencewood.com
description: "Mobile web maker. Design, urbanism, futurology, and the human condition."
baseurl: ""
url: "http://terrencewood.com"

# Build settings
markdown: kramdown
permalink: pretty


# prose.io

prose: 
  metadata:
    _posts:
      - name: "noindex"
      field:
       element: "checkbox"
       label: "prevent google indexing"
       value: false
